version: '3'
services:
  flask-app1:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      NODE_ID: 1
  flask-app2:
    build: .
    ports:
      - "5002:5001"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      NODE_ID: 2