@endpoint = http://localhost:5001

POST {{endpoint}}/addBlock
Content-Type: application/json

{
    "location": "Stockholm",
    "name": "My Space"
}
###

GET {{endpoint}}/hello
Content-Type: application/json
###

GET {{endpoint}}/file
Content-Type: application/json

