@endpoint = http://localhost:5001

POST {{endpoint}}/addBlock
Content-Type: application/json

{
    "location": "Stockholm",
    "name": "My Space"
}
###

GET {{endpoint}}/getPeers
Content-Type: application/json
###

GET {{endpoint}}/getSelf
Content-Type: application/json
###

GET {{endpoint}}/getChain
Content-Type: application/json
###
